LearningASP/Controllers/CustomerController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using LearningASP.DataServices;
using LearningASP.Models.Services;
using LearningASP.Models;

namespace LearningASP.Controllers
{
    public class CustomerController : Controller
    {
        public ActionResult Index()
        {
            List<Customer> customers = DatabaseHelper.Instance.GetAllCustomers();
            return View(customers);
        }
        public ActionResult Edit(int id)
        {
            Customer cs = DatabaseHelper.Instance.GetCustomer(id);
            return View(cs);
        }
        [HttpPost]
        public ActionResult Edit(Customer customer)
        {
            if (customer != null)
            {
                DatabaseHelper.Instance.UpdateCustomer(customer);
                return RedirectToAction("Index");
            }
            return View();
        }
        public ActionResult Delete()
        {
            return View();
        }
        public ActionResult Delete(Customer customer)
        {
            if (customer != null)
            {
                DatabaseHelper.Instance.RemoveCustomer(customer.CustomerID);
                return RedirectToAction("Index");
            }
            return View();
        }
        public ActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public ActionResult Create(Customer customer)
        {
            if (customer != null)
            {
                DatabaseHelper.Instance.AddCustomer(customer);
                return RedirectToAction("Index");
            }
            return View();
        }
    }
}

LearningASP/Controllers/ItemController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using LearningASP.Models.Services;
using LearningASP.DataServices;
using LearningASP.CommonCode;

namespace LearningASP.Controllers
{
    public class ItemController : Controller
    {
        public ActionResult Index()
        {
            List<Item> list = DatabaseHelper.Instance.GetAllItems();
            return View(list);
        }
        public ActionResult Create()
        {
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Item item)
        {
            if (item != null)
            {
                DatabaseHelper.Instance.AddItem(item);
                return RedirectToAction("Index");
            }
            return View();
        }
        public ActionResult Edit(int id)
        {
            Item item = DatabaseHelper.Instance.GetItem(id);
            return View(item);
        }
        [HttpPost]
        public ActionResult Edit(Item item)
        {
            DatabaseHelper.Instance.UpdateItem(item);
            return RedirectToAction("Index");
        }
        //public ActionResult Delete()
        //{
        //    return View();
        //}
        public ActionResult Delete(int Id)
        {
            JsonResult result = new JsonResult();
            result.JsonRequestBehavior = JsonRequestBehavior.AllowGet;
            try
            {
                DatabaseHelper.Instance.RemoveItem(Id);
            }
            catch (Exception ex)
            {

            }
            return RedirectToAction("Index");
        }
    }
}

LearningASP/Views/Customer/Create.cshtml
@model LearningASP.DataServices.Customer

@{
    ViewBag.Title = "Create";
}

<h2>Add New Customer</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.CustomerName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CustomerName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CustomerName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Phone, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Phone, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Phone, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Address, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextAreaFor(model => model.Address, new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Address, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            <input hidden name="Status" value="Active" type="text" />
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-primary" />
                <input type="button" href="@Url.Action("Index","Customer")" value="Back" class="btn btn-default" />
            </div>
        </div>
    </div>
}

LearningASP/Views/Customer/Delete.cshtml
@model LearningASP.DataServices.Customer

@{
    ViewBag.Title = "Delete";
}

<h2>Delete Customer</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.CustomerName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CustomerName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Phone)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Phone)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Address)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Address)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Status)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Status)
        </dd>

    </dl>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-danger" /> |
            <input type="button" href="@Url.Action("Index","Item")" value="Back" class="btn btn-default" />
        </div>
    }
</div>

LearningASP/Views/Customer/Edit.cshtml
@model LearningASP.DataServices.Customer

@{
    ViewBag.Title = "Edit";
}

<h2>Edit Customer</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

<div class="form-horizontal">
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    @Html.HiddenFor(model => model.CustomerID)

    <div class="form-group">
        @Html.LabelFor(model => model.CustomerName, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.CustomerName, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.CustomerName, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Phone, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Phone, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Phone, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Address, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Address, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Address, "", new { @class = "text-danger" })
        </div>
    </div>
    @{
      
        string active = Model.Status== "Active" ? "selected" : string.Empty;
        string inactive = Model.Status == "Deleted" ? "selected" : string.Empty;
    }
    <div class="form-group">
        <label class="control-label col-md-2" for="Status">Status</label>
        <div class="col-md-10">

            <select class="form-control" name="Status">
                <option @active value="Active">
                    Active
                </option>
                <option @inactive value="Deleted">
                    Delete
                </option>
            </select>
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Update" class="btn btn-sm btn-primary" />
            <input type="button" value="Back" href="@Url.Action("Index","Item")" class="btn btn-sm btn-default" />
        </div>
    </div>
</div>
}

LearningASP/Views/Customer/Index.cshtml
@model IEnumerable<LearningASP.DataServices.Customer>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


<div class="container">

    <div class="row ">
        <div class="col-md-12">
            <h2>
                Customers<a class="pull-right" href="@Url.Action("Create","Customer")"><span class=" btn btn-sm btn-primary">Add New</span></a>
            </h2>
            <div class="table-responsive">
                <table class="table table-responsive">
                    <tr>
                        <th>
                            @Html.DisplayNameFor(model => model.CustomerName)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.Phone)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.Address)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.Status)
                        </th>
                        <th>Actions</th>
                    </tr>

                    @foreach (var cs in Model)
                    {
                        <tr>
                            <td>
                                @Html.DisplayFor(modelItem => cs.CustomerName)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => cs.Phone)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => cs.Address)
                            </td>

                            @{
                                if (cs.Status == "Active")
                                {
                                    <td>
                                        <span class="label label-success">@cs.Status</span>
                                    </td>
                                }
                                else
                                {
                                    <td>
                                        <span class="label label-danger">@cs.Status</span>
                                    </td>
                                }
                            }

                            <td>
                                <a class="btn btn-sm btn-primary" href="@Url.Action("Edit", "Customer", new { id = cs.CustomerID })">Edit</a>
                                <a class="btn btn-sm btn-danger" href="@Url.Action("Delete", "Customer", new { id = cs.CustomerID })">Delete</a>

                            </td>
                        </tr>
                    }

                </table>
            </div>
        </div>
    </div>
</div>